sudo: false
language: python
cache: pip
python:
    - 3.6-dev
    - nightly

matrix:
  allow_failures:
    - python: nightly

install:
    - wget https://raw.githubusercontent.com/sormuras/bach/master/install-jdk.sh
    - chmod +x ./install-jdk.sh
    - ./install-jdk.sh -f 10
    - pip install pycodestyle
    - pip install asyncpg
    - pip install .
script:
    - python -m unittest -v
    - pycodestyle cr8

notifications:
    email: false
