---
jobs:
  - job: 'Test'
    pool:
      vmImage: 'Ubuntu 16.04'
    strategy:
      matrix:
        Python36:
          python.version: '3.6'
        Python37:
          python.version: '3.7'
      maxParallel: 4

    steps:
      - task: UsePythonVersion@0
        inputs:
          versionSpec: '$(python.version)'
          architecture: 'x64'

      - script: |
          python -m pip install --upgrade pip
          pip install pycodestyle asyncpg "nose2[coverage_plugin]"
          pip install .
        displayName: 'Install dependencies'

      - script: |
          nose2 --with-coverage \
            --coverage-report xml \
            --coverage-report html \
            --plugin nose2.plugins.junitxml \
            --junit-xml tests
          pycodestyle cr8
        displayName: 'test'

      - task: PublishTestResults@2
        inputs:
          testResultsFiles: 'nose2-junit.xml'
          testRunTitle: 'Publish test results for Python $(python.version)'

      - task: PublishCodeCoverageResults@1
        inputs:
          codeCoverageTool: Cobertura
          summaryFileLocation: '$(System.DefaultWorkingDirectory)/**/coverage.xml'
          reportDirectory: '$(System.DefaultWorkingDirectory)/**/htmlcov'

  - job: 'Publish'
    dependsOn: 'Test'
    pool:
      vmImage: 'Ubuntu 16.04'

    steps:
      - task: UsePythonVersion@0
        inputs:
          versionSpec: '3.x'
          architecture: 'x64'

      - script: |
          python -m pip install twine wheel
          python setup.py sdist bdist_wheel
          twine check dist/*.tar.gz
        displayName: 'Build sdist and wheel'
