---
jobs:
  - job: 'Test'
    pool:
      vmImage: 'Ubuntu 16.04'
    strategy:
      matrix:
        Python36:
          python.version: '3.6'
        Python37:
          python.version: '3.7'
      maxParallel: 4
    steps:
      - task: UsePythonVersion@0
        inputs:
          versionSpec: '$(python.version)'
          architecture: 'x64'
      - script: |
          python -m pip install --upgrade pip
          pip install pycodestyle asyncpg pytest pytest-cov
          pip install .
        displayName: 'Install dependencies'
      - script: |
          pytest --doctest-modules --junitxml=junit/test-results.xml --cov=com --cov-report=xml --cov-report=html
          pycodestyle cr8
        displayName: 'test'
      - task: PublishTestResults@2
        inputs:
          testResultsFiles: '**/test-*.xml'
          testRunTitle: 'Publish test results for Python $(python.version)'
      - task: PublishCodeCoverageResults@1
        inputs:
          codeCoverageTool: Cobertura
          summaryFileLocation: '$(System.DefaultWorkingDirectory)/**/coverage.xml'
          reportDirectory: '$(System.DefaultWorkingDirectory)/**/htmlcov'
  - job: 'Publish'
    dependsOn: 'Test'
    pool:
      vmImage: 'Ubuntu 16.04'
    steps:
      - task: UsePythonVersion@0
        inputs:
          versionSpec: '3.x'
          architecture: 'x64'
      - script: python setup.py sdist
        displayName: 'Build sdist'
      - script: |
          python -m pip install wheel
          python setup.py bdist_wheel
        displayName: 'Build wheel'
